openapi: '3.0.2'
info:
  title: Filmes API
  description: Uma API para gerenciar informações sobre filmes, incluindo operações para listar, adicionar e gerenciar filmes e usuários.
  version: '1.0'
servers:
  - url: http://localhost:8080/movies
paths:
  /{id}:
    get:
      summary: Obtém um filme pelo ID
      description: Retorna um único filme pelo seu ID, incluindo detalhes como diretor, atores e metascore.
      parameters:
        - name: id
          in: path
          description: Identificador único do filme.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detalhes do filme retornados com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        '404':
          description: Filme não encontrado.
components:
  schemas:
    Movie:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Identificador único do filme, usado para referenciar o filme em operações da API.
        titulo:
          type: string
          description: Título do filme, como exibido em materiais de marketing e mídia.
        ano:
          type: integer
          description: Ano de lançamento do filme, importante para ordenação e referência histórica.
        duracaoEmMinutos:
          type: integer
          description: A duração total do filme em minutos.
        genero:
          type: array
          items:
            type: string
          description: Lista de gêneros aos quais o filme pertence, útil para filtragem e busca.
        diretor:
          type: string
          description: Nome do diretor do filme, crucial para reconhecimento de autoria e estilo.
        roteiristas:
          type: array
          items:
            type: string
          description: Lista dos nomes dos roteiristas do filme, essencial para crédito de criação de conteúdo.
        atores:
          type: array
          items:
            type: string
          description: Lista dos principais atores do filme, chave para identificação de elenco e atratividade do filme.
        poster:
          type: string
          format: uri
          description: URL para um poster do filme, oferece uma representação visual para o usuário.
        metascore:
          type: integer
          description: Pontuação agregada de críticas do filme, oferece uma métrica de qualidade e recepção crítica.
        videoUrl:
          type: string
          format: uri
          description: URL direta para o vídeo ou trailer do filme, permite acesso imediato ao conteúdo visual.
        category:
          type: string
          description: Categoria principal do filme, utilizada para simplificar a organização e busca por tipo de conteúdo.
